[package]
name = "rukeeb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.8"
usbd-human-interface-device = "0.5"
itertools = "0.13.0"
